### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by dperry** [dperry/app#1]
```
details:
  msg: Peace cannot be kept by force, it can only be achieved by understanding - Albert Einstein
id: 02ad95b2b32b48f6bc6285605219c397
level: info
message: Unsolicited random wisdom of the moment
resource:
  account_name: admin
  id: null
  type: wisdom
source:
  base_url: http://api:8228
  host_id: anchore-quickstart
  request_id: null
  service_name: apiext
timestamp: '2024-03-17T15:09:12.839202'
type: system.test.random_wisdom
```
