### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by dperry** [dperry/app#2]
```
details:
  msg: Against the assault of laughter, nothing can stand - Mark Twain
id: 4a7409ccc58648f1a15258b73930bc31
level: info
message: Unsolicited random wisdom of the moment
resource:
  account_name: admin
  id: null
  type: wisdom
source:
  base_url: http://api:8228
  host_id: anchore-quickstart
  request_id: null
  service_name: apiext
timestamp: '2024-03-17T15:09:23.950676'
type: system.test.random_wisdom
```
