### ISSUE TITLE
[ANCHORE] Unsolicited random wisdom of the moment

### ISSUE THREAD

**Issue by dperry** [dperry/app#7]
```
details:
  msg: The truth is rarely pure and never simple - Oscar Wilde
id: 96c737b6726b4ea8803dd0c4c054eb19
level: info
message: Unsolicited random wisdom of the moment
resource:
  account_name: admin
  id: null
  type: wisdom
source:
  base_url: http://api:8228
  host_id: anchore-quickstart
  request_id: null
  service_name: apiext
timestamp: '2024-11-12T10:57:15.742048'
type: system.test.random_wisdom
```
